### ISSUE TITLE
loadSingleSampleNyu error

### ISSUE THREAD

**Issue by weiguochow** [poier/PreView#1] opened 2018-05-01 23:18 UTC
Hi, I have changed the dataset root, then run `python main_run.py`. But there was an error

```
  File "/home/alex/PhD/1_PoseEstimation/PreView/source/data/NyuHandPoseDataset.py", line 569, in loadSingleSampleNyu
    dpt = dpt + sigmaNoise * rng.randn(dpt.shape[0], dpt.shape[1])
UnboundLocalError: local variable 'dpt' referenced before assignment
```
Can you help me to fix it. Thank you!!!

**Comment by poier** [comment] 2018-05-09 14:43
Hi,
I just freshly downloaded the dataset to see if I can reproduce the error then, but couldn't.
Can you post (or send me) the full output?

**Comment by dan0910** [comment] 2018-05-18 00:52
Hi, @poier 
The same situation as @weiguochow , I have the same error using the NYU dataset. 
Here is the full output:

> /usr/bin/python2.7 /home/dan/Documents/PreView-master/source/main_run.py
> Init NYU Dataset...
> NYU Dataset init done.
> Using 43641 samples for training
>   43641 labeled
> Init NYU Dataset...
> NYU Dataset init done.
> Using 2440 samples for validation
> Init NYU Dataset...
> NYU Dataset init done.
> Using 8252 samples for test
> Train Epoch: 1 [128/43641 (0%)]	Loss/sample: 216.578003
> Train Epoch: 1 [1408/43641 (3%)]	Loss/sample: 210.926117
> Train Epoch: 1 [2688/43641 (6%)]	Loss/sample: 214.969437
> Train Epoch: 1 [3968/43641 (9%)]	Loss/sample: 213.137909
> Traceback (most recent call last):
>   File "/home/dan/Documents/PreView-master/source/main_run.py", line 151, in <module>
>     model_discriminator=model_d)
>   File "/home/dan/Documents/PreView-master/source/trainer/SuperTrainer.py", line 62, in train
>     optim_type=args.optim_type)
>   File "/home/dan/Documents/PreView-master/source/trainer/ViewPredAndHaPeTrainer.py", line 128, in train
>     self.train_epoch(epoch, model, optimizer, out_crop_size)
>   File "/home/dan/Documents/PreView-master/source/trainer/ViewPredAndHaPeTrainer.py", line 163, in train_epoch
>     in enumerate(self.train_loader):
>   File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 267, in __next__
>     return self._process_next_batch(batch)
>   File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 301, in _process_next_batch
>     raise batch.exc_type(batch.exc_msg)
> UnboundLocalError: Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 55, in _worker_loop
>     samples = collate_fn([dataset[i] for i in batch_indices])
>   File "/home/dan/Documents/PreView-master/source/data/NyuHandPoseDataset.py", line 230, in __getitem__
>     minRatioInside=self.args_data.min_ratio_inside).data[0]
>   File "/home/dan/Documents/PreView-master/source/data/NyuHandPoseDataset.py", line 571, in loadSingleSampleNyu
>     dpt = dpt + sigmaNoise * rng.randn(dpt.shape[0], dpt.shape[1])
> UnboundLocalError: local variable 'dpt' referenced before assignment

**Comment by weiguochow** [comment] 2018-05-18 02:47
@dan0910 Hi, I think maybe you set the config "use_cache" equals True. But there are not exists the cache file, then dpt got an error. That means the cache file not load correctly.

**Comment by poier** [comment] 2018-05-18 11:42
Hi,
I could reproduce the error now. 
It seems to be a threading issue in connection with the "cache" as @weiguochow mentioned. By default, we use multiple workers for loading the data. Since a "cache" file is generated (and written) when a file should be loaded for the first time, the threads/processes might interfere in a way that such a situation occurs. (Unfortunately, simple locking didn't solve the issue for me since PyTorch uses different processes for this.)

There are several solutions to this issue, but I would currently suggest to just once load all data by using a single process. So, that the cache is properly written and, then, go on with standard training. To use a single process, you just need to set the value of `num_workers` accordingly. I just updated the code so that this can be set in config.py now (using `args.num_loader_workers`).

Another solution would of course be to not use the cache at all, i.e., set 
`args_data.use_pickled_cache = False` in config_data_nyu.py. However, this will probably slow down training and testing.

**Comment by vaeXu** [comment] 2018-06-01 08:25
hi @poier @dan0910 @weiguochow  , i am willing  to try to train this project but where can i get the original_pickled,   as => args_data.nyu_data_basepath_pickled = "/path/to/NyuDataset/original_data_pickled"

**Comment by poier** [comment] 2018-06-01 09:13
Hi,
it is generated automatically as soon as you set `args_data.use_pickled_cache = True`, which is set to False by default. 
You can also do the training without using the cache/binary files (i.e., keeping `args_data.use_pickled_cache = False`). Training/testing can be faster when using the binary files, however.
Also, see the corresponding sections in the readme ("Training/Testing speed" and "Faster training/testing on NYU dataset").

**Comment by vaeXu** [comment] 2018-06-04 02:30
hi@poier ，thank you, your answer has benefited me a lot. i try to train the project but the error occur.why  it appear  'ran out of input'.
Train Epoch: 1 [16768/43641 (38%)]	Loss/sample: 0.951136
Loss_D: 0.4467; Loss_G: 0.9511; D(x): 1.3327; D(G(z)): 0.3780 / -0.1301
Train Epoch: 1 [18048/43641 (41%)]	Loss/sample: 0.932010
Loss_D: 0.3501; Loss_G: 0.9320; D(x): 0.7042; D(G(z)): -0.3193 / 0.2220
Data file exists but failed to load. File: /home/jhd/face_recognition/xjh_pytorch/PreView/source/results/default/run00_default/config/train/real/cam1/frame_30838_allFalse.pgz
Train Epoch: 1 [19328/43641 (44%)]	Loss/sample: 0.951263
Loss_D: 0.1940; Loss_G: 0.9513; D(x): 0.8226; D(G(z)): -0.0555 / -0.0592
Traceback (most recent call last):
  File "main_run.py", line 137, in <module>
    model_discriminator=model_d)
  File "/home/jhd/face_recognition/xjh_pytorch/PreView/source/trainer/SuperTrainer.py", line 69, in train
    optim_type=args.optim_type)
  File "/home/jhd/face_recognition/xjh_pytorch/PreView/source/trainer/AdversarialViewPredAndHaPeTrainer.py", line 128, in train
    self.train_epoch(epoch, model, model_discriminator, optimizer, optimizer_d, out_crop_size)
  File "/home/jhd/face_recognition/xjh_pytorch/PreView/source/trainer/AdversarialViewPredAndHaPeTrainer.py", line 175, in train_epoch
    in enumerate(self.train_loader):
  File "/home/jhd/face_recognition/anaconda3/envs/face3_cp/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 267, in __next__
    return self._process_next_batch(batch)
  File "/home/jhd/face_recognition/anaconda3/envs/face3_cp/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 301, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
EOFError: Traceback (most recent call last):
  File "/home/jhd/face_recognition/anaconda3/envs/face3_cp/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 55, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/jhd/face_recognition/anaconda3/envs/face3_cp/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 55, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/jhd/face_recognition/xjh_pytorch/PreView/source/data/NyuHandPoseDataset.py", line 230, in __getitem__
    minRatioInside=self.args_data.min_ratio_inside).data[0]
  File "/home/jhd/face_recognition/xjh_pytorch/PreView/source/data/NyuHandPoseDataset.py", line 551, in loadSingleSampleNyu
    dpt = pickle.load(f)
EOFError: Ran out of input

**Comment by poier** [comment] 2018-06-04 12:03
Hi,
it seems that the file `/home/jhd/face_recognition/xjh_pytorch/PreView/source/results/default/run00_default/config/train/real/cam1/frame_30838_allFalse.pgz` is corrupted. You should delete it and re-run the code. The file will be re-generated automatically. 
I would just recommend you to re-run with a single loader-worker at first and/or without random sampling (see the section about "Faster training/testing on NYU dataset" in the README)

**Comment by vaeXu** [comment] 2018-06-15 01:17
I had solved the problem, thank you.

**Comment by poier** [comment] 2018-06-15 08:34
Happy to hear that. I'm closing the issue then.

**Closed as completed by poier** 2018-06-15 08:34 UTC
